version: 0.2
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate
  
  build:
    commands:
      - terraform apply --auto-approve -replace "module.aviatrix-controller-build.aws_instance.aviatrixcontroller[0]"